name: injectable_micropackages
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart. Also enables the support for micro packages concept, supporting di inside of those sub-projects
version: 1.0.10
homepage: https://github.com/GoncaloPT/injectable
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  get_it: ^6.1.1
dev_dependencies:
  pedantic: ^1.11.0