name: injectable
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 1.0.6
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get_it: ">=4.0.0 <6.0.0"

dev_dependencies:
  pedantic: ^1.9.0