builders:
  injectable_builder:
    import: "package:injectable_generator/builder.dart"
    builder_factories: ["injectableBuilder"]
    build_extensions: { ".dart": [".injectable.json"] }
    auto_apply: dependents
    runs_before: ["injectable_generator|injectable_config_builder|micro_packages_scout"]
    build_to: cache
  injectable_config_builder:
    import: "package:injectable_generator/builder.dart"
    builder_factories: ["injectableConfigBuilder"]
    build_extensions: { ".dart": [".config.dart"] }
    runs_before: [ "micro_packages_scout" ]
    auto_apply: dependents
    build_to: source
  micro_packages_builder:
    import: "package:injectable_generator/builder.dart"
    builder_factories: ["microPackagesBuilder"]
    build_extensions: { ".dart": [ ".micropackage.config.part" ] }
    auto_apply: dependents
    build_to: source
