name: injectable_generator
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 1.0.5
homepage: https://github.com/Milad-Akarie/injectable

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.0.0
  source_gen: ^0.9.0
  path: ^1.6.0
  glob: ^1.1.7
  analyzer: ">=0.39.2 <0.40.4"
  code_builder: "^3.4.1"
  injectable: 
    #^1.0.5
     path: ../injectable
  collection: ^1.14.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  build_runner: ^1.0.0
  build_test:

