name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-injectable-micropackages:
    defaults:
      run:
        working-directory: injectable_micropackages
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
  build-injectable-generator-micropackages:
    defaults:
      run:
        working-directory: injectable_generator_micropackages
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get

