name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-injectable-micropackages:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: go to injectable_micropackages
      run: cd injectable_micropackages
    - name: Install dependencies
      run: pub get
  build-injectable-generator-micropackages:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: go to injectable_micropackages
        run: cd injectable_generator_micropackages
      - name: Install dependencies
        run: pub get

